export const BAD_PHRASES = [
  "No vales la pena.",
  "¿Qué has hecho con tu vida?",
  "Eres un fracaso.",
  "Nunca llegarás a nada.",
  "Estás roto más allá de la reparación.",
  "Eres una carga para todos los que te rodean.",
  "Eres una causa perdida.",
  "Eres desesperanzado.",
  "Solo estás desperdiciando espacio.",
  "Nunca vas a mejorar.",
  "Eres incapaz de ser feliz.",
  "Siempre vas a estar solo.",
  "No eres digno de amor.",
  "Solo eres una decepción.",
  "Solo te estás engañando a ti mismo.",
  "Estás demasiado dañado para ser arreglado.",
  "Solo eres un fracaso.",
  "Nunca escaparás de este ciclo.",
  "Nunca encontrarás paz.",
  "Estás destinado a autodestruirte.",
  "No tienes remedio.",
  "Eres inútil.",
  "Nunca serás feliz.",
  "No tienes ningún valor.",
  "Eres una vergüenza.",
  "Nunca lograrás nada.",
  "Eres un desperdicio de tiempo.",
  "Nadie te necesita.",
  "Nunca serás suficiente.",
  "No eres capaz de hacer nada bien.",
  "Eres una carga para tu familia.",
  "Nunca conseguirás tus sueños.",
  "No tienes talento.",
  "Eres un fracaso constante.",
  "Eres una decepción para todos.",
  "No sirves para nada.",
  "Siempre estarás solo.",
  "Nunca serás amado.",
  "Eres incapaz de cambiar.",
  "Eres una pérdida de espacio.",
  "Nadie te quiere.",
  "No tienes futuro.",
  "Eres una causa perdida.",
  "Nunca serás importante.",
  "Eres una decepción.",
  "No puedes hacer nada bien.",
  "Eres un peso muerto.",
  "No eres nadie.",
  "Eres un error.",
  "Eres una ruina.",
  "Nunca serás feliz.",
  "Eres un caso perdido.",
  "Nunca serás aceptado.",
  "Eres una sombra de lo que podrías ser.",
  "Nunca lograrás tus metas.",
  "Eres una ilusión rota.",
  "Eres un desastre.",
  "No tienes esperanza.",
  "Eres un fracaso viviente.",
  "Nunca serás suficiente para nadie.",
  "Eres un perdedor.",
  "Eres un caso sin esperanza.",
  "No tienes salvación.",
  "Eres una ruina emocional.",
  "Nunca serás completo.",
  "Eres un desastre total.",
  "Nunca serás feliz con nadie.",
  "Eres una causa perdida para siempre.",
  "Eres un fracaso sin redención.",
  "Nunca dejarás de ser un desastre.",
  "Nadie te quiere aquí.",
  "No tienes remedio.",
  "Nunca harás nada significativo.",
  "Eres un desastre andante.",
  "No sabes hacer nada bien.",
  "Solo causas problemas.",
  "Eres un perdedor.",
  "Nunca lograrás nada bueno.",
  "Eres inútil.",
  "No mereces ser feliz.",
  "Solo traes tristeza a los demás.",
  "Eres un error.",
  "Nadie puede ayudarte.",
  "Estás destinado al fracaso.",
  "Todo lo que tocas lo arruinas.",
  "Nunca serás suficiente.",
  "Eres un fracaso constante.",
  "No puedes hacer nada correctamente.",
  "Eres una vergüenza.",
  "Solo causas dolor.",
  "Nunca superarás tus problemas.",
  "No tienes valor.",
  "Eres una carga emocional.",
  "Eres una sombra de lo que podrías haber sido.",
  "No puedes ser salvado.",
  "Eres un parásito.",
  "No eres digno de respeto.",
  "Eres un caso perdido.",
  "No mereces el amor de nadie.",
  "Solo traes desdicha.",
  "Eres una causa inútil.",
  "Nunca serás feliz.",
  "Eres una decepción constante.",
  "No tienes ningún propósito.",
  "Eres una mancha en la vida de los demás.",
  "No puedes ser amado.",
  "Eres un fracaso sin esperanza.",
  "Eres una carga financiera.",
  "No tienes futuro.",
  "Eres una ruina emocional.",
  "Nunca serás una persona completa.",
  "Eres una fuente de tristeza.",
  "Eres un peso muerto.",
  "No tienes solución.",
  "Eres una decepción para todos.",
  "No puedes hacer nada bien.",
  "Eres un lastre.",
  "No mereces apoyo.",
  "Eres un desastre irreparable.",
  "Nunca serás alguien importante.",
];
